version: '3.8'

services:
    msdocs-server:
      build:
        context: .
        dockerfile: ./dockerfile
      ports:
        - "8000:8000"
      networks:
        - mkdocs-network

networks:
  mkdocs-network:
    driver: bridge