version: '3.8'

services:

  backend-mariadb:
    tty: true
    entrypoint: ./entrypoint.sh
    image: laurentlienhard/fusionsuite-backend:latest
    ports:
      - "80:80"
      - "3306:3306"

  frontend:
    tty: true
    entrypoint: ./entrypoint.sh
    image: laurentlienhard/fusionsuite-frontend:latest
    ports:
      - "8080:80"
